# Read data from the filesystem at CEDA/Jasmin.
projects:
  CMIP6:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /badc/cmip6/data
        dirname_template: "{project}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*.nc"
  CMIP5:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /badc/cmip5/data
        dirname_template: "{project.lower}/{product}/{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}*.nc"
  CMIP3:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /badc/cmip3_drs/data
        dirname_template: "{project.lower}/output/{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{short_name}/{ensemble}/{version}"
        filename_template: "{short_name}_*.nc"
  CORDEX:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /badc/cordex/data
        dirname_template: "{project}/output/{domain}/{institute}/{driver}/{exp}/{ensemble}/{institute}-{dataset}/{rcm_version}/{mip}/{short_name}/{version}"
        filename_template: "{short_name}_{domain}_{driver}_{exp}_{ensemble}_{institute}-{dataset}_{rcm_version}_{mip}*.nc"
  obs4MIPs:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /gws/nopw/j04/esmeval/obsdata-v2
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{short_name}_*.nc"
  OBS6:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /gws/nopw/j04/esmeval/obsdata-v2
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{project}_{dataset}_{type}_{version}_{mip}_{short_name}[_.]*nc"
  OBS:
    data:
      badc:
        type: "esmvalcore.local.LocalDataSource"
        rootpath: /gws/nopw/j04/esmeval/obsdata-v2
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{project}_{dataset}_{type}_{version}_{mip}_{short_name}[_.]*nc"
