# Read data from the ACCESS model in its native format.
projects:
  ACCESS:
    data:
      access-sub-dataset:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: ~/climate_data
        dirname_template: "{dataset}/{sub_dataset}/{exp}/{modeling_realm}/netCDF"
        filename_template: "{sub_dataset}.{freq_attribute}-*.nc"
      access-ocean:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: ~/climate_data
        dirname_template: "{dataset}/{sub_dataset}/{exp}/{modeling_realm}/netCDF"
        filename_template: "ocean_{freq_attribute}.nc-*"
