# Read data from the ESA Climate Data Centre (ESA CCI) using xcube.
# More information available at
# https://xcube.readthedocs.io/en/latest/dataaccess.html#esa-climate-data-centre-esa-cci-cciodp-ccizarr-esa-cci-kc.
projects:
  external:
    data:
      ccizarr:
        type: "esmvalcore.io.xcube.XCubeDataSource"
        data_store_id: "ccizarr"
        priority: 1
      esa-cci-kc:
        type: "esmvalcore.io.xcube.XCubeDataSource"
        data_store_id: "esa-cci-kc"
        priority: 2
      cciodp:
        type: "esmvalcore.io.xcube.XCubeDataSource"
        data_store_id: "cciodp"
        priority: 3
