# Read CMIP, obs4MIPs, native6, OBS6, and OBS data from the filesystem at NCI.
projects:
  CMIP6:
    data:
      oi10: &cmip6
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/oi10/replicas
        dirname_template: "{project}/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{version}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}_{grid}*.nc"
      fs38:
        <<: *cmip6
        rootpath: /g/data/fs38/publications
      xp65:
        <<: *cmip6
        rootpath: /g/data/xp65/public/apps/esmvaltool/replicas
  CMIP5:
    data:
      r87: &cmip5
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/r87/DRSv3/CMIP5
        dirname_template: "{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{version}/{short_name}"
        filename_template: "{short_name}_{mip}_{dataset}_{exp}_{ensemble}*.nc"
      al33:
        <<: *cmip5
        rootpath: /g/data/al33/replicas/CMIP5/combined
      rr3: &cmip5-default
        <<: *cmip5
        rootpath: /g/data/rr3/publications
        dirname_template: "{project}/{product}/{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{version}/{short_name}"
      xp65:
        <<: *cmip5-default
        rootpath: /g/data/xp65/public/apps/esmvaltool/replicas
  CMIP3:
    data:
      local:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/r87/DRSv3/CMIP3
        dirname_template: "{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{ensemble}/{short_name}/{latestversion}"
        filename_template: "{short_name}_*.nc"
  obs4MIPs:
    data:
      local:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{short_name}_*.nc"
  native6:
    data:
      local:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/xp65/public/apps/esmvaltool/native6
        dirname_template: "Tier{tier}/{dataset}/{version}/{frequency}/{short_name}"
        filename_template: "*.nc"
  OBS6:
    data:
      local:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{project}_{dataset}_{type}_{version}_{mip}_{short_name}[_.]*nc"
  OBS:
    data:
      local:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: /g/data/ct11/access-nri/replicas/esmvaltool/obsdata-v2
        dirname_template: "Tier{tier}/{dataset}"
        filename_template: "{project}_{dataset}_{type}_{version}_{mip}_{short_name}[_.]*nc"
