# Default logging configuration.

# Note that most logging options are still configured in the file
# esmvalcore/config/logging.yml and are not yet configurable for users.

logging:
  log_progress_interval: 0.
