# workflow that performs a validity check of CITATION.cff file
# author: Abel Siqueira, GH: @abelsiqueira

name: CFF File Validator

permissions: {}

on:
  push:
    paths:
      - CITATION.cff
  schedule:
    - cron: "0 0 1 * *"

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    if: github.repository == 'ESMValGroup/ESMValCore' # avoid GAs in forks
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084 # 2.0.0
        with:
          args: "--validate"
